---
version: "0.1"

services:
  foundry:
    image: foundry-docker
    build: .
    restart: always
    volumes:
      - type: bind
        source: /home/pi/Documentos/foundryVTTData
        target: /root/foundryVTTData
      - type: bind
        source: /home/pi/Documentos/foundryVTTSource
        target: /root/foundryVTTSource
    ports: 
      - "443:30000"