---
version: "0.1"

services:
  foundry:
    build: .
    restart: always
    volumes:
      - /home/pi/Documentos/foundryVTTData:/root/foundryVTTData:rw
      - /home/pi/Documentos/foundryVTTSource:/root/foundryVTTSource:rw
    ports: 
      - "443:30000"