---
services:
  foundry:
    build: .
    restart: always
    volumes:
      - ./foundryVTTData:/root/foundryVTTData:rw
      - ./foundryVTTSource:/root/foundryVTTSource:rw
    ports: 
      - "443:30000"
  ftp:
    image: forumi0721/alpine-vsftpd
    restart: always
    environment:
      USER_NAME: master
      USER_PASSWD: YOUR_PASSWORD
      FTP_SHARE: /data
      FTP_BANNER: Welcome
    ports:
      - "20:20"
      - "21:21"
      - "60000-60099:60000-60099"
    volumes: 
      - ./foundryVTTData:/data/foundryData