---
services:
  foundry:
    build: .
    restart: always
    volumes:
      - ./foundryVTTData:/root/foundryVTTData:rw
      - ./foundryVTTSource:/root/foundryVTTSource:rw
    ports: 
      - "443:30000"
  ftp:
    image: forumi0721/alpine-vsftpd
    restart: always
    environment:
      - USER_NAME: master
      - USER_PASSWD: /run/secrets/ftp_password
      - FTP_SHARE: /data
      - FTP_BANNER: Welcome
    ports:
      - "21:21"
    volumes: 
      - ./foundryVTTData:/data/foundryData
    secrets:
      - ftp_password
secrets:
   ftp_password:
     file: ftp_password