---
version: "0.1"

services:
  foundry:
    build: .
    restart: always
    volumes:
      - ./foundryVTTData:/root/foundryVTTData:rw
      - ./foundryVTTSource:/root/foundryVTTSource:rw
    ports: 
      - "443:30000"