---
version: "0.1"

services:
  foundry:
    build: .
    restart: always
    volumes:
      - ./foundryVTTData:/root/foundryVTTData:rw
      - ./foundryVTTSource:/root/foundryVTTSource:rw
    ports: 
      - "443:30000"
  ftp:
    image: fauria/vsftpd
    restart: always
    environment:
      - FTP_USER: master
      - FTP_PASS: /run/secrets/ftp_password
    ports:
      - "21:21"
    volumes: ./foundryVTTData:/home/vsftpd
    secrets:
      - ftp_password
secrets:
   ftp_password:
     file: ftp_password